#!/bin/bash

alarm() {
  local timeout=$1; shift;
  # execute command, store PID
  bash -c "$@" &
  local pid=$!
  # sleep for $timeout seconds, then attempt to kill PID
  {
    sleep "$timeout"
    kill $pid 2> /dev/null
  } &
  wait $pid 2> /dev/null 
  return $?
}


scan() {
  if [[ -z $1 || -z $2 ]]; then
    echo "Usage: scan <host> <port, ports, or port-range>"
    echo "Example: scan google.com 79-81"
    return
  fi

  local host=$1
  local ports=()
  
  case $2 in
    *-*)
      IFS=- read start end <<< "$2"
      for ((port=start; port <= end; port++)); do
        ports+=($port)
      done
      ;;
    *,*)
      IFS=, read -ra ports <<< "$2"
      ;;
    *)
      ports+=($2)
      ;;
  esac

  
  for port in "${ports[@]}"; do
    alarm 1 "echo >/dev/tcp/$host/$port" &&
      echo "$port/tcp open" ||
      echo "$port/tcp closed"
  done
}
